// Generated by CoffeeScript 1.3.1
(function() {
  var $;

  $ = jQuery;

  $.fn.getCursorPosition = function() {
    var Sel, SelLength, el, pos;
    pos = 0;
    el = $(this).get(0);
    if (document.selection) {
      el.focus();
      Sel = document.selection.createRange();
      SelLength = document.selection.createRange().text.length;
      Sel.moveStart('character', -el.value.length);
      pos = Sel.text.length - SelLength;
    } else if (el.selectionStart || el.selectionStart === 0) {
      pos = el.selectionStart;
    }
    return pos;
  };

  $.fn.number = function() {
    var count, h, i, map, num, order, sel, selector, t, _i, _j, _len, _len1, _ref, _results;
    selector = 'H1,H2,H3,H4,H5,H6,OL,UL,LI';
    order = selector.split(',');
    map = {};
    for (i = _i = 0, _len = order.length; _i < _len; i = ++_i) {
      sel = order[i];
      map[sel] = {
        c: 0,
        pos: i
      };
    }
    num = function(tag) {
      var c, i, t;
      return ((function() {
        var _j, _ref, _results;
        _results = [];
        for (i = _j = 0, _ref = map[tag].pos; 0 <= _ref ? _j <= _ref : _j >= _ref; i = 0 <= _ref ? ++_j : --_j) {
          if ((c = map[(t = order[i])].c) !== 0 && (t !== 'OL' && t !== 'UL')) {
            _results.push(c);
          }
        }
        return _results;
      })()).join(',');
    };
    count = function(sel) {
      var e, i, _j, _ref, _ref1, _results;
      e = map[sel];
      e.c++;
      _results = [];
      for (i = _j = _ref = e.pos + 1, _ref1 = order.length; _ref <= _ref1 ? _j < _ref1 : _j > _ref1; i = _ref <= _ref1 ? ++_j : --_j) {
        _results.push(map[order[i]].c = 0);
      }
      return _results;
    };
    _ref = $(selector, this);
    _results = [];
    for (i = _j = 0, _len1 = _ref.length; _j < _len1; i = ++_j) {
      h = _ref[i];
      t = h.tagName;
      count(t);
      if (t !== 'OL' && t !== 'UL') {
        _results.push($(h).attr('data-number', num(t)));
      } else {
        _results.push(void 0);
      }
    }
    return _results;
  };

  $.fn.generateToc = function() {
    var e, i, numbers;
    return '<ul>' + ((function() {
      var _i, _len, _ref, _results;
      _ref = $('[data-number]', this);
      _results = [];
      for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
        e = _ref[i];
        numbers = $(e).attr('data-number').split(',');
        _results.push("<li><a href=\"#" + e.id + "\"><" + e.tagName + ">\n  " + (numbers.join('. ')) + ". " + (e.textContent || e.innerText) + "\n</" + e.tagName + "></a></li>");
      }
      return _results;
    }).call(this)).join('') + '</ul>';
  };

}).call(this);
